name: Build Docker Image and Notify Telegram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t price-monitor-bot .

    - name: Send Telegram Notification
      run: |
        MESSAGE="✅ New Docker build completed successfully for priceMonitorBot.\nCommit: ${{ github.event.head_commit.message }}\nRepo: ${{ github.repository }}"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.CHAT_ID }}&text=${MESSAGE}"
